version: '3'

services:
  sqlserver:
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Strong(!)Password

  amstramgram:
    build: .
    ports:
      - "4242:80"
    links:
      - sqlserver
    depends_on:
      - sqlserver
